#!/usr/bin/env python3
"""Sign and persist ssdf.audit chain-head checkpoints (MEC-565).

I/O shell around `ssdf_mcp_query.checkpoint_orchestrator.compute_next_checkpoint`
(pure decision logic, unit-tested on its own): reads each chain's currently
surviving rows and its previous checkpoint from ClickHouse as the
`ssdf_checkpoint` identity (022_audit_checkpoints.sql), asks the orchestrator
what the next checkpoint should say, shells out to the Rust
`mecmcp-audit-checkpoint` binary (mechubsec/mecmcp, crates/mecmcp-audit) to
sign it -- deterministic, no model in the loop -- and inserts the signed
result into `ssdf.audit_checkpoints`.

Key management (v1): a local Ed25519 private key file, generated by
`mecmcp-audit-keygen` and readable only by the account this script runs as
(the signing binary enforces 0600 and refuses otherwise -- the same
fail-closed check `mecmcp-audit`'s evidence signing already uses). Operators
who want HSM- or KMS-backed signing replace `--binary`/`CHECKPOINT_SIGNER_BIN`
with a wrapper that speaks the same stdin/stdout contract; this script has no
opinion on how the key is stored beyond "a path mecmcp-audit-checkpoint can
read".

Run periodically (e.g. daily) from the deploy's scheduler of choice -- this
script does not schedule itself, matching the signing binary's own stance
that it is not the orchestrator either.

Self-verification before signing: this job must not sign a chain it has not
itself confirmed clean. `compute_next_checkpoint`'s own docstring says
checkpointing an unverified chain is "the caller's mistake to avoid" -- this
is that check, and `compute_next_checkpoint` separately refuses outright on
the one tamper shape it can detect directly while walking the chain, rather
than quietly picking a branch. `CH_CHECKPOINT_VERIFY_KEY_PATH` is required
(not merely recommended) so this self-verification step can always anchor
past an already checkpointed, since-expired predecessor the same way
verify_audit.py does (including bridging through ssdf.audit_evidence); a job
that ran without it would silently skip self-verifying any chain whose
genesis has expired, rather than fail closed up front.

Usage (from services/mcp-query, where the package is installed):
    export CH_HOST=... CH_CHECKPOINT_PASSWORD=...
    export CHECKPOINT_SIGNING_KEY_PATH=/etc/ssdf/checkpoint-signing.key
    export CH_CHECKPOINT_VERIFY_KEY_PATH=/etc/ssdf/checkpoint-verify.key
    uv run python scripts/checkpoint_audit.py [--binary mecmcp-audit-checkpoint]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field

from ssdf_common.config import ConfigError, require_tls_or_loopback
from ssdf_mcp_query.checkpoint_orchestrator import (
    ForkDetectedError,
    compute_next_checkpoint,
    rows_unreachable_from_previous,
)
from ssdf_mcp_query.checkpoint_verify import (
    Checkpoint,
    CheckpointVerificationError,
    load_verifying_key,
    verify_checkpoint_signature,
)
from ssdf_mcp_query.verify_audit import group_key, verify_tier

# Same shape verify_audit.py reads (_VERIFY_COLUMNS): compute_next_checkpoint
# only needs tier/args/prev_hash/row_hash, but verify_tier's content-integrity
# check needs every field compute_row_hash folds into a row's hash -- this
# job must see exactly what verify_audit.py would see to self-verify
# meaningfully.
_ROW_COLUMNS = [
    "ts",
    "principal",
    "tier",
    "tool",
    "args",
    "data_classes",
    "decision",
    "row_count",
    "error",
    "client_name",
    "model_id",
    "actor_type",
    "prev_hash",
    "row_hash",
]
_CHECKPOINT_COLUMNS = [
    "tier",
    "server_id",
    "row_count",
    "head_row_hash",
    "checkpoint_ts",
    "signature",
    "key_id",
]

# The payload fields the signer is handed and must echo back unchanged: a
# signer that silently substitutes a different row_count/head_row_hash/etc.
# would otherwise sign and commit something this job never asked for.
_PAYLOAD_FIELDS = ("tier", "server_id", "row_count", "head_row_hash", "checkpoint_ts")


@dataclass
class RunResult:
    """What one `run()` invocation did, per chain."""

    inserted: list[dict] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)


def fetch_rows_by_chain(client) -> dict[tuple[str, str], list[dict]]:
    """Every chain's currently-stored, hashed rows, grouped by (tier, server_id).

    Excludes pre-chain legacy rows (row_hash == '', same convention as
    verify_audit.verify_tier) -- they were never part of any chain a
    checkpoint could anchor.
    """
    res = client.query(
        f"SELECT {', '.join(_ROW_COLUMNS)} FROM ssdf.audit WHERE row_hash != '' ORDER BY ts ASC"
    )
    by_chain: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for values in res.result_rows:
        row = dict(zip(_ROW_COLUMNS, values))
        by_chain[group_key(row)].append(row)
    return by_chain


# How far back to read ssdf.audit_evidence for bridge material. Matches
# verify_audit.py's own bound -- the walk only ever needs to reach from the
# current TTL boundary to the nearest checkpoint, which under a daily
# schedule is at most a few days.
_EVIDENCE_BRIDGE_LOOKBACK_DAYS = 120


def fetch_evidence_rows_by_chain(client, now: dt.datetime) -> dict[tuple[str, str], list[dict]]:
    """Each chain's evidence-tier rows available as bridge material for
    self-verification, grouped the same way as `fetch_rows_by_chain`.
    Requires `ssdf_checkpoint` to hold SELECT on `ssdf.audit_evidence`
    (022_audit_checkpoints.sql / 023_audit_evidence.sql)."""
    if now.tzinfo is None:
        now = now.replace(tzinfo=dt.timezone.utc)
    since = now - dt.timedelta(days=_EVIDENCE_BRIDGE_LOOKBACK_DAYS)
    res = client.query(
        f"SELECT {', '.join(_ROW_COLUMNS)} FROM ssdf.audit_evidence "
        "WHERE ts >= {since:DateTime64(3)} ORDER BY ts ASC",
        parameters={"since": since},
    )
    by_chain: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for values in res.result_rows:
        row = dict(zip(_ROW_COLUMNS, values))
        by_chain[group_key(row)].append(row)
    return by_chain


def fetch_previous_checkpoints(client) -> dict[tuple[str, str], dict]:
    """Each chain's most recent prior checkpoint, as compute_next_checkpoint expects.

    Ordering by checkpoint_ts ascending and overwriting `latest` as we go
    means the last write per key wins -- the same "most recent" rule
    verify_audit._select_checkpoint_anchor uses (max by checkpoint_ts).
    """
    res = client.query(
        f"SELECT {', '.join(_CHECKPOINT_COLUMNS)} "
        "FROM ssdf.audit_checkpoints ORDER BY checkpoint_ts ASC"
    )
    latest: dict[tuple[str, str], dict] = {}
    for values in res.result_rows:
        row = dict(zip(_CHECKPOINT_COLUMNS, values))
        latest[(row["tier"], row["server_id"])] = row
    return latest


def fetch_checkpoints_by_chain(client) -> dict[tuple[str, str], list[Checkpoint]]:
    """Every chain's full checkpoint history, for self-verification --
    `verify_tier` needs every checkpoint, not just the latest, to find the
    one whose head matches a dangling prev_hash."""
    res = client.query(
        f"SELECT {', '.join(_CHECKPOINT_COLUMNS)} "
        "FROM ssdf.audit_checkpoints ORDER BY checkpoint_ts ASC"
    )
    by_chain: dict[tuple[str, str], list[Checkpoint]] = defaultdict(list)
    for values in res.result_rows:
        row = dict(zip(_CHECKPOINT_COLUMNS, values))
        checkpoint = Checkpoint(
            tier=row["tier"],
            server_id=row["server_id"],
            row_count=int(row["row_count"]),
            head_row_hash=row["head_row_hash"],
            checkpoint_ts=row["checkpoint_ts"],
            signature=row["signature"],
            key_id=row["key_id"],
        )
        by_chain[(checkpoint.tier, checkpoint.server_id)].append(checkpoint)
    return by_chain


def load_checkpoint_verifying_key() -> bytes | None:
    """The checkpoint verifying key for self-verification, or None when it is
    not configured (fail closed to skipping self-verification for chains
    whose genesis has expired, not to an exception -- a fresh chain that
    still has its genesis needs no anchor and self-verifies fine either
    way)."""
    path = os.environ.get("CH_CHECKPOINT_VERIFY_KEY_PATH")
    if not path:
        return None
    try:
        return load_verifying_key(path)
    except CheckpointVerificationError as exc:
        print(f"warning: could not load checkpoint verifying key: {exc}", file=sys.stderr)
        return None


def format_checkpoint_ts(now: dt.datetime) -> str:
    """Millisecond-precision RFC3339 with a literal 'Z', matching the Rust
    signer's expected `checkpoint_ts` field (checkpoint.rs's usage string)."""
    if now.tzinfo is None:
        now = now.replace(tzinfo=dt.timezone.utc)
    now = now.astimezone(dt.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"


def build_payload(pending, now: dt.datetime) -> dict:
    """The unsigned checkpoint JSON handed to mecmcp-audit-checkpoint on stdin."""
    return {
        "tier": pending.tier,
        "server_id": pending.server_id,
        "row_count": pending.row_count,
        "head_row_hash": pending.head_row_hash,
        "checkpoint_ts": format_checkpoint_ts(now),
    }


def sign_checkpoint(
    binary: str,
    key_path: str,
    payload: dict,
    verifying_key: bytes | None = None,
) -> dict:
    """Shell out to the Rust signer. Deterministic, no model in the loop.

    Fails closed: a non-zero exit, a timeout, or unparsable/incomplete stdout
    raises rather than letting an unsigned or partially-signed checkpoint
    reach the caller's insert path.

    Two additional checks, run after a successful parse: the signer must
    echo back the exact content fields it was asked to sign
    (a signer that silently substituted a different row_count/head_row_hash
    would otherwise go uncaught), and, when `verifying_key` is given, its
    signature must itself verify -- a buggy or compromised signer producing
    output that merely *parses* like a checkpoint must not reach the insert
    path either.
    """
    try:
        proc = subprocess.run(
            [binary, key_path],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise RuntimeError(f"could not run {binary!r}: {exc}") from exc
    if proc.returncode != 0:
        raise RuntimeError(f"{binary} failed: {proc.stderr.strip()}")
    try:
        signed = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"{binary} produced invalid JSON: {exc}") from exc
    missing = [c for c in _CHECKPOINT_COLUMNS if c not in signed]
    if missing:
        raise RuntimeError(f"{binary} output missing field(s): {missing}")

    for field_name in _PAYLOAD_FIELDS:
        if field_name in payload and signed[field_name] != payload[field_name]:
            raise RuntimeError(
                f"{binary} returned {field_name}={signed[field_name]!r}, "
                f"expected {payload[field_name]!r}"
            )

    if verifying_key is not None:
        checkpoint = Checkpoint(
            tier=signed["tier"],
            server_id=signed["server_id"],
            row_count=int(signed["row_count"]),
            head_row_hash=signed["head_row_hash"],
            checkpoint_ts=signed["checkpoint_ts"],
            signature=signed["signature"],
            key_id=signed["key_id"],
        )
        try:
            verify_checkpoint_signature(checkpoint, verifying_key)
        except CheckpointVerificationError as exc:
            raise RuntimeError(f"{binary} produced an invalid signature: {exc}") from exc

    return signed


def insert_checkpoint(client, signed: dict) -> None:
    client.insert(
        "ssdf.audit_checkpoints",
        [[signed[c] for c in _CHECKPOINT_COLUMNS]],
        column_names=_CHECKPOINT_COLUMNS,
    )


def run(
    client,
    binary: str,
    key_path: str,
    now: dt.datetime | None = None,
    verifying_key: bytes | None = None,
) -> RunResult:
    """Checkpoint every chain that has rows newer than its last checkpoint.

    Self-verifies each chain with `verify_tier` before checkpointing it -- a
    chain `compute_next_checkpoint` has not first been confirmed clean on is
    never signed; it is skipped (fail closed) instead, surfaced via
    `RunResult.skipped`.
    """
    now = now or dt.datetime.now(dt.timezone.utc)
    rows_by_chain = fetch_rows_by_chain(client)
    previous_by_chain = fetch_previous_checkpoints(client)
    checkpoints_by_chain = fetch_checkpoints_by_chain(client)
    evidence_by_chain = fetch_evidence_rows_by_chain(client, now)
    result = RunResult()
    # Walk every chain that has EITHER surviving rows OR a checkpoint, not
    # just `rows_by_chain`'s keys -- a chain whose rows were all removed
    # from ssdf.audit has no entry there, and skipping it would also skip
    # the head_unreachable backstop below for it.
    all_chains = set(rows_by_chain) | set(checkpoints_by_chain)
    for chain in sorted(all_chains):
        rows = rows_by_chain.get(chain, [])
        issues = verify_tier(
            rows,
            checkpoints=checkpoints_by_chain.get(chain, []),
            bridge_rows=evidence_by_chain.get(chain, []),
            verifying_key=verifying_key,
            now=now,
        )
        if issues:
            print(
                f"skipping chain tier={chain[0]} server={chain[1]!r}: "
                f"{len(issues)} unresolved issue(s), refusing to checkpoint an unverified chain",
                file=sys.stderr,
            )
            result.skipped.append(chain)
            continue
        previous = previous_by_chain.get(chain)
        if previous is not None and verifying_key is not None:
            previous_checkpoint = Checkpoint(
                tier=previous["tier"],
                server_id=previous["server_id"],
                row_count=int(previous["row_count"]),
                head_row_hash=previous["head_row_hash"],
                checkpoint_ts=previous["checkpoint_ts"],
                signature=previous["signature"],
                key_id=previous["key_id"],
            )
            try:
                verify_checkpoint_signature(previous_checkpoint, verifying_key)
            except CheckpointVerificationError as exc:
                print(
                    f"skipping chain tier={chain[0]} server={chain[1]!r}: "
                    f"previous checkpoint does not verify, refusing to extend it: {exc}",
                    file=sys.stderr,
                )
                result.skipped.append(chain)
                continue
        try:
            pending = compute_next_checkpoint(rows, previous)
        except ForkDetectedError as exc:
            print(
                f"skipping chain tier={chain[0]} server={chain[1]!r}: {exc}",
                file=sys.stderr,
            )
            result.skipped.append(chain)
            continue
        if pending is None:
            row_hashes = {r["row_hash"] for r in rows}
            head_unreachable = (
                previous is not None
                and previous["head_row_hash"] not in row_hashes
                and not any(r["prev_hash"] == previous["head_row_hash"] for r in rows)
            )
            stray = rows_unreachable_from_previous(rows, previous)
            if head_unreachable or stray:
                print(
                    f"skipping chain tier={chain[0]} server={chain[1]!r}: "
                    "previous checkpoint's head is unreachable from the chain's current "
                    "rows, refusing to checkpoint without a verified anchor",
                    file=sys.stderr,
                )
                result.skipped.append(chain)
            continue
        signed = sign_checkpoint(
            binary, key_path, build_payload(pending, now), verifying_key=verifying_key
        )
        insert_checkpoint(client, signed)
        result.inserted.append(signed)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--binary",
        default=os.environ.get("CHECKPOINT_SIGNER_BIN", "mecmcp-audit-checkpoint"),
        help="path to the mecmcp-audit-checkpoint binary",
    )
    args = parser.parse_args()

    key_path = os.environ.get("CHECKPOINT_SIGNING_KEY_PATH")
    password = os.environ.get("CH_CHECKPOINT_PASSWORD")
    if not key_path:
        print("CHECKPOINT_SIGNING_KEY_PATH is required", file=sys.stderr)
        return 2
    if not password:
        print("CH_CHECKPOINT_PASSWORD is required", file=sys.stderr)
        return 2
    if not os.environ.get("CH_CHECKPOINT_VERIFY_KEY_PATH"):
        print("CH_CHECKPOINT_VERIFY_KEY_PATH is required", file=sys.stderr)
        return 2

    verifying_key = load_checkpoint_verifying_key()
    if verifying_key is None:
        print("could not load CH_CHECKPOINT_VERIFY_KEY_PATH", file=sys.stderr)
        return 2

    host = os.environ.get("CH_HOST", "127.0.0.1")
    secure = os.environ.get("CH_SECURE", "").strip().lower() in ("1", "true")
    try:
        require_tls_or_loopback(host, secure)
    except ConfigError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    import clickhouse_connect

    kwargs: dict = {}
    if secure:
        kwargs["interface"] = "https"
        ca_file = os.environ.get("CH_CA_FILE")
        if ca_file:
            kwargs["ca_cert"] = ca_file

    client = clickhouse_connect.get_client(
        host=host,
        port=int(os.environ.get("CH_PORT", "8123")),
        username="ssdf_checkpoint",
        password=password,
        database="ssdf",
        **kwargs,
    )

    try:
        result = run(client, args.binary, key_path, verifying_key=verifying_key)
    except RuntimeError as exc:
        print(f"checkpointing failed: {exc}", file=sys.stderr)
        return 1

    for cp in result.inserted:
        writer = f" server={cp['server_id']}" if cp["server_id"] else ""
        print(
            f"checkpointed tier={cp['tier']}{writer} "
            f"row_count={cp['row_count']} head={cp['head_row_hash'][:16]}…"
        )
    print(f"{len(result.inserted)} chain(s) checkpointed, {len(result.skipped)} skipped")
    return 1 if result.skipped else 0


if __name__ == "__main__":
    sys.exit(main())
