"""Known-answer cross-implementation tests for checkpoint_verify.py.

The fixture below (key + signature) was generated by the actual Rust
binaries, not reimplemented independently on the Python side:

    cargo build -p mecmcp-audit --bins   # mechubsec/mecmcp, v0.26.0 checkout
    PUB=$(./mecmcp-audit-keygen priv.key)
    echo '{"tier":"evidence","server_id":"rustsdcmcp-606","row_count":42,
           "head_row_hash":"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
           "checkpoint_ts":"2026-09-28T00:00:00.000Z"}' \\
        | ./mecmcp-audit-checkpoint priv.key

This is the same precedent as audit_chain.py's `dedup_token` known-answer
vectors: two independent encodings that merely "look equivalent" is exactly
how a byte-level mismatch hides until a real signature fails to verify.
"""

from __future__ import annotations

import base64

import pytest

from ssdf_mcp_query.checkpoint_verify import (
    Checkpoint,
    CheckpointVerificationError,
    verify_checkpoint_signature,
)

_VERIFYING_KEY_B64 = "eq9vdjiCq9yRMn3C7MQmI6QFOkxq52Bb4PRExbLQ0GM="
_OTHER_KEY_B64 = "AtqHG8dIiOhQanjTfmfJcED8/U6XfQLxeyANTVzwusk="  # a different Ed25519 pubkey


def _fixture() -> Checkpoint:
    return Checkpoint(
        tier="evidence",
        server_id="rustsdcmcp-606",
        row_count=42,
        head_row_hash="abcdef0123456789" * 4,
        checkpoint_ts="2026-09-28T00:00:00.000Z",
        signature=(
            "ynK96u2ASYHKQIBzfKs1U9AZBYtBQQ/NjRr5rIKnrl2uL2WSOh"
            "+nWi3pNc3DwUYhNiKnuWjEeOSRKaZqK/dPCQ=="
        ),
        key_id="7b5c53a1eeb8048b",
    )


def _key(b64: str) -> bytes:
    return base64.b64decode(b64)


def test_known_answer_signature_verifies():
    verify_checkpoint_signature(_fixture(), _key(_VERIFYING_KEY_B64))


def test_wrong_key_fails():
    with pytest.raises(CheckpointVerificationError):
        verify_checkpoint_signature(_fixture(), _key(_OTHER_KEY_B64))


def test_tampered_row_count_fails():
    tampered = Checkpoint(**{**_fixture().__dict__, "row_count": 43})
    with pytest.raises(CheckpointVerificationError):
        verify_checkpoint_signature(tampered, _key(_VERIFYING_KEY_B64))


def test_tampered_head_hash_fails():
    tampered = Checkpoint(**{**_fixture().__dict__, "head_row_hash": "0" * 64})
    with pytest.raises(CheckpointVerificationError):
        verify_checkpoint_signature(tampered, _key(_VERIFYING_KEY_B64))


def test_malformed_signature_raises_not_crashes():
    tampered = Checkpoint(**{**_fixture().__dict__, "signature": "not-base64!!"})
    with pytest.raises(CheckpointVerificationError):
        verify_checkpoint_signature(tampered, _key(_VERIFYING_KEY_B64))


def test_malformed_key_raises():
    with pytest.raises(CheckpointVerificationError):
        verify_checkpoint_signature(_fixture(), b"too-short")
